#!/usr/bin/env ash

set -e

main() {
  mkdir -p /home/builder/.abuild;
  if [ ! -z ${CI_PROJECT_DIR+x} ]; then
      cd $CI_PROJECT_DIR;
      export REPODEST=$CI_PROJECT_DIR/output;
      mkdir -p $REPODEST;
  else
      mkdir -p "$REPODEST";
  fi;
  abuild-apk update
  [ "$RSA_PRIVATE_KEY" ] && {
    echo -e "$RSA_PRIVATE_KEY" > "/home/builder/.abuild/$RSA_PRIVATE_KEY_NAME"
    export PACKAGER_PRIVKEY="/home/builder/.abuild/$RSA_PRIVATE_KEY_NAME"
  }
  sudo chown -R builder:abuild /home/builder/package
  sudo chown -R builder:abuild $REPODEST

  exec abuild -r
}

main 
